version: '3.8'

services:
  denso_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: sk_mpc_container
    tty: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/dockeruser/.Xauthority:rw
      - ./ros2_ws:/workspace
      - ./fastdds_udp_only.xml:/etc/fastdds.xml:ro
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/dockeruser/.Xauthority
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_LOCALHOST_ONLY=0
      - FASTRTPS_DEFAULT_PROFILES_FILE=/etc/fastdds.xml
    user: "1000:1000"
