services:
  denso_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1003
        GROUP_ID: 1003
    container_name: sk_mpc_container
    tty: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/dockeruser/.Xauthority:rw
      - ./ros2_ws:/workspace
      - ./cyclonedds.xml:/workspace/cyclonedds.xml:ro
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/dockeruser/.Xauthority
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=0
      - CYCLONEDDS_NETWORK_INTERFACE_ADDRESS=enp10s0 # 确保这是你的网卡名
      - CYCLONEDDS_ALLOW_MULTICAST=true
      - CYCLONEDDS_URI=file:///workspace/cyclonedds.xml
    user: "1003:1003"
