FROM ros:humble

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

# 安装系统和 ROS 2 工具依赖
RUN apt update && apt install -y \
    build-essential git curl wget sudo locales \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-rosdep \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-xacro \
    ros-humble-tf-transformations \
    ros-humble-joint-state-publisher-gui \
    net-tools iputils-ping nano \
    ros-humble-demo-nodes-cpp ros-humble-demo-nodes-py \
    ros-humble-rmw-cyclonedds-cpp
    
RUN apt update && apt install -y \
    net-tools iputils-ping nano \
    ros-humble-moveit \
    ros-humble-moveit-common \
    ros-humble-moveit-ros-move-group \
    ros-humble-moveit-ros-planning \
    ros-humble-moveit-ros-visualization \
    && apt clean

# 设置 locale
RUN locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

# 初始化 rosdep
RUN rosdep update

# 创建匹配 host 用户的非 root 用户（UID/GID = 1005）
ARG USER_ID=1005
ARG GROUP_ID=1005
RUN groupadd -g ${GROUP_ID} dockeruser && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash dockeruser && \
    usermod -aG sudo dockeruser && \
    echo "dockeruser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# 准备工作区目录并授予权限
RUN mkdir -p /workspace/ws_denso_ros2/src && \
    chown -R dockeruser:dockeruser /workspace

# 切换到普通用户并设为默认工作目录
USER dockeruser
WORKDIR /workspace/denso_ros2_ws

# 默认 source 环境配置
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc && \
    echo "source /workspace/denso_ros2_ws/install/setup.bash" >> ~/.bashrc
